(function(){
"use strict";

var window = window || self;

var ObjectCloner = {};
window.ObjectCloner = ObjectCloner;

ObjectCloner.clone = function (objectToClone, type, schema) {
    var newObject = jQuery.extend(true, {}, objectToClone);

    var pointerToSchemaMap = SchemaExtractorFactory.get().extract(objectToClone, schema);
    for (var jsonPointer in pointerToSchemaMap) {
        var subSchema = pointerToSchemaMap[jsonPointer];
        var autoGeneratedFieldNode = SchemaUtil.getDeepCordraSchemaProperty(subSchema, 'type', 'autoGeneratedField');
        if (!autoGeneratedFieldNode) continue;
        JsonUtil.replaceJsonAtPointer(newObject, jsonPointer, null);
    }

    //Remove any server set properties
    //Remove any payloads, file names.
    return newObject;
};

})();
