#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Cordra documentation build configuration file, created by
# sphinx-quickstart on Fri Nov 10 11:32:35 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.todo', 'recommonmark']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# source_suffix = '.rst'
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown'
}

# The master toctree document.
master_doc = 'index'

# General information about the project.
import datetime
year = str(datetime.date.today().year)
month = str(datetime.date.today().year)
project = 'Cordra'
copyright = ' ' + month +' ' + year + ' Corporation for National Research Initiatives' + 'hdl:20.1000/113'
author = 'Corporation for National Research Initiatives'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0'
# The full version, including alpha/beta/rc tags.
# The version.txt file is created by the gradle task :cordra-technical-manual:buildVersionInfo
try:
    with open('version.txt', 'r') as f:
        release = f.readline().strip()
except EnvironmentError:
    release = ''

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
# pygments_style = 'vs'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

html_show_sourcelink = False

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation. https://alabaster.readthedocs.io/en/latest/customization.html
#
# html_theme_options = {
#     'show_powered_by': False,
#     'logo': 'keyhole3.png',
#     'logo_name': True,
#     'fixed_sidebar': True,
#     'font_family': 'Trebuchet MS,Geneva,Arial,Helvetica,SunSans-Regular,sans-serif',
#     'head_font_family': 'Trebuchet MS,Geneva,Arial,Helvetica,SunSans-Regular,sans-serif',
#     'extra_nav_links': {
#         'Cordra.org': 'https://cordra.org',
#         'Handle.Net Registry': 'https://handle.net/'
#     }
# }

html_theme_options = {
    'show_powered_by': False,
    # 'logo': 'keyhole3.png',
    # 'logo_name': True,
    'fixed_sidebar': True,
    'font_family': 'Open Sans,Montserrat,Trebuchet MS,Geneva,Arial,Helvetica,SunSans-Regular,sans-serif',
    'head_font_family': 'Open Sans,Montserrat,Trebuchet MS,Geneva,Arial,Helvetica,SunSans-Regular,sans-serif',
    'sidebar_collapse': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [ 'minimal-fixes.css' ]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'searchbox.html',
        'navigation.html',
    ]
}
# html_sidebars = {
#     '**': [
#         'about.html',
#         'relations.html',
#         'donate.html',
#     ]
# }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Cordradoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # Gets rid of blank pages in between.
    'classoptions': ',openany,oneside',
    'sphinxsetup': 'verbatimhintsturnover=true',
    'papersize': 'letterpaper',
    'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble.
    'preamble': r'''
        \setcounter{secnumdepth}{3}
        \setcounter{tocdepth}{2}
        \usepackage{charter}
        \usepackage[defaultsans]{lato}
        \usepackage{inconsolata}
        \renewcommand{\familydefault}{\sfdefault}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \renewcommand{\sectionmark}[1]{ \markright{#1}{} }
        \usepackage{textcomp}
        ''',
    'maketitle': r'''
        \pagenumbering{Roman} %%% to avoid page 1 conflict with actual page 1
        \begin{titlepage}
        \par\noindent\rule{\textwidth}{.5pt}
        \rule[.8\baselineskip]{\textwidth}{.5pt}

        \vspace*{20mm}
        \textbf{\Huge {Cordra Software Technical Manual}}

        \Huge \textbf{{Version 2}}
        \vspace{20mm}

        \vfill

        \begin{flushright}
        \vspace{40mm}
        \Large \textbf{{Corporation for National Research Initiatives}}

        \small Released on \today

        \end{flushright}

        \par\noindent\rule{\textwidth}{.5pt}
        \rule[.8\baselineskip]{\textwidth}{.5pt}

        \clearpage
        %% License information

        \vspace*{10mm}
        \normalsize \textcopyright\ Corporation for National Research Initiatives, 2019. All Rights Reserved.

        \vspace*{2mm}
        \normalsize Cordra v2 software is subject to the terms of the Cordra (Version 2) License Agreement, which
        is made available here: https://hdl.handle.net/20.1000/117.

        \vspace*{2mm}
        Please send questions or comments to support@cordra.org.

        \vfill

        \end{titlepage}
        \clearpage
    ''',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

latex_logo = '_static/img/logo/cordra-primary-blue.png'
# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Cordra.tex', 'Cordra Technical Manual',
     'Corporation for National Research Initiatives \\thanks{' + u'\u00a9' + ' ' + copyright + '}', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'cordra', 'Cordra',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Cordra', 'Cordra',
     author, 'Cordra', 'Cordra is open source software built on the digital object foundation, and \
     offers a distinct experience to software developers who intend to build scalable infrastructures \
     for managing digital objects with resolvable identifiers, and at scale.',
     'Miscellaneous'),
]
